### ISSUE TITLE
Setup project structure

### ISSUE THREAD

**Issue by CodeLawd** [ApexHauz/ApexHauz#1]
# `@todo`

- [x] Create the project structure
- [x] Configure the app to use mysql database
- [x] Finish setting up github repo
- [ ] Add members to the repo
- [ ] Assign task to members
